config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'doctors#index'

  resources :doctors
  resources :patients
  resources :appointments, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates_presence_of :first_name, :last_name, :gender

  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates_presence_of :first_name, :last_name, :age, :race, :gender

  has_many :appointments, dependent: :destroy
  has_one :doctor, through: :appointments

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :doctors, dependent: :destroy
  has_many :patients, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
    @doctor = Doctor.all.map { |d| [d.first_name, d.id] }
    @patient = Patient.all.map { |f| [f.first_name, f.id] }
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)

      if @appointment.save
        redirect_to doctors_path
      else
        render :new
      end

  end

  def destroy
    appointment = Appointment.find(params[:id])
    appointment.destroy
    redirect_to doctor_path(appointment.doctor_id)
  end

  private
  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :time)

  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = current_user.doctors.all
  end

  def new
    @doctor = current_user.doctors.new
  end

  def create
    @doctor = current_user.doctors.new(doctor_params)
    if @doctor.save
      redirect_to doctors_path
    else
      render :new
    end

  end

  def show
  end

  def edit

  end

  def update

    if @doctor.update(doctor_params)
      redirect_to doctors_path
    else
      render :edit
    end

  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private
    def set_doctor
      @doctor = current_user.doctors.find(params[:id])
    end

    def doctor_params
      binding.pry
      params.require(:doctor).permit(:first_name, :last_name, :gender)
    end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to patients_path
    else
      render :new
    end

  end

  def show
  end

  def edit

  end

  def update

    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit
    end

  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :race, :age, :gender, :insurance)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/new.html.erb
<div class="container">
<h1> Add a Patient </h1>
<hr />

<%= form_for @appointment do |f| %>
  <h3>
    Doctors:<%= f.select :doctor_id, options_for_select(@doctor) %>
    <%= link_to 'New Doctor', new_doctor_path %>
  </h3>
  <h3>
    Patients:<%= f.select :patient_id, options_for_select(@patient) %>
    <%= link_to 'New Patient', new_patient_path %>
  </h3>

  <%= f.date_field :date, required: true %>
  <%= f.submit nil, class: 'btn' %>
<% end %>

<hr />
<%= link_to 'All Doctors', doctors_path %> |
<%= link_to 'All Patients', patients_path %>
</div>

app/views/doctors/_form.html.erb
<div class="container">
<%= form_for(doctor) do |f| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.select :gender, ['Male', 'Female'] %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
  <div>
  <%= link_to 'Back', doctors_path %>
</div>
<% end %>
</div>

app/views/doctors/edit.html.erb
<h1>Edit Doctor Info</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/index.html.erb
<div class="container">
<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.full_name %></td>
        <td><%= link_to 'Show', doctor_path(doctor) %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

<%= link_to 'Make An Appointment', new_appointment_path %>
</div>

app/views/doctors/new.html.erb
<div class="container">
<h1>New Doctor Form</h1>

<%= render 'form', doctor: @doctor %>
</div>

app/views/doctors/show.html.erb
<h1> Doctor: <%= @doctor.full_name %> - <%= @doctor.gender %> </h1>

<% if @doctor.patients.empty? %>
  <h5>No Patients Found</h5>

<% else %>

  <h5>Patients</h5>
  <% @doctor.patients.each do |patient| %>
    <% @doctor.appointments.each do |appointment| %>
    <li>
      <%= patient.full_name %> at <%= appointment.time %>
      <%= link_to 'Remove', patient_path(patient), method: :delete, data: {confirm: 'Really remove this ingredient?'} %>
    </li>
    <% end %>
  <% end %>


<% end %>

<%= link_to 'All Doctors', doctors_path %> |
<%= link_to 'Edit', edit_doctor_path %> |
<%= link_to 'Make An Appointment', new_appointment_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrOfficeAppointments</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Doctors Office</a>
        <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to 'Doctors', doctors_path %></li>
          <li><%= link_to 'Patients', patients_path %></li>
          <li><%= link_to 'Appointments', new_appointment_path %></li>
        </ul>
        <ul class="side-nav" id="mobile">
          <li><%= link_to 'Doctors', doctors_path %></li>
          <li><%= link_to 'Patients', patients_path %></li>
          <li><%= link_to 'Appointments', new_appointment_path %></li>
        </ul>
      </div>
    </nav
    <div class="container">
    </div>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<div class="container">
<%= form_for(patient) do |f| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
  </div>


  <div class="field">
    <%= f.label :race %>
    <%= f.text_field :race %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
  <div>
  <%= link_to 'Back', :back %>
</div>
<% end %>

</div>

app/views/patients/edit.html.erb
<h1>Patients#edit</h1>
<p>Find me in app/views/patients/edit.html.erb</p>

app/views/patients/index.html.erb
<div class="container">
<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.full_name %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>
<%= link_to 'Make An Appointment', new_appointment_path %>
<%= link_to 'All Doctors', doctors_path %>
</div>

app/views/patients/new.html.erb
<div class="container">
<h1> New Patient </h1>

<%= render 'form', patient: @patient %>
</div>

app/views/patients/show.html.erb
<div class="container">
<h1> Patient: <%= @patient.full_name %> </h1>

<%= link_to 'All Doctors', doctors_path %>
</div>